# Generated by Django 4.2.8 on 2023-12-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_notification_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
