# Generated by Django 4.2.8 on 2023-12-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_notification_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
    ]
